name: Question
description: Having Trouble - ONLY OSS maintainers of other projects OR ACTIVE project sponsors can use this! If you aren't one of these, expect the ban hammer to fall.  NO QUESTIONS ABOUT PREVIEW/BETA VERSIONS PLEASE! 
body:
- type: textarea
  attributes:
    label: Question
    description: Please be a concise as possible
    validations:
      required: true
- type: checkboxes
  id: terms
  attributes:
    label: Code of Conduct
    description: By submitting this issue, you agree that you are a project sponsor or active OSS maintainer 
    options:
      - label: I agree
        required: true